### PR TITLE
Milestone 1

### PR DESCRIPTION
**Pull request by Bismarck-GM**
## Milestone 1:

- Created the main layout using bootstrap.
- Finished main styles and added responsiveness.
- Used bootstrap mainly for display, aligning, and layout.
- Styled everything according to the target webpage to clone.
- Uploaded tons of images to the site and FontAwesome for Social Icons.

I didn't get the part that it was supposed to be responsive with bootstrap so I made it "Desktop-first". It was hard to tackle but the end product works almost like the original.

PS: Now I've learned to always start with mobile and main layout + "jumps" according to the device and/or width. **LAYOUT LAYOUT LAYOUT.**

### CODE REVIEW

**Review by trekab — CHANGES_REQUESTED** [review]
# Changes Required:
Hi @Bismarck-GM, you have an impressive job on this project so far! :+1:  However, there are some adjustments you need to make to complete this project. These are;

- [x] As soon as the main navigation links disappear, a hamburger icon should appear for medium and small screens.
- [x] For small screens, `TOP STORY` should be the first article on the page. (Compare [original page](https://www.newsweek.com/))
- [x] There are many more places in your CSS where you can rely on bootstrap classes. For example, you can use [responsive breakpoints](https://getbootstrap.com/docs/4.3/layout/overview/#responsive-breakpoints) and avoid all custom media queries in your CSS. 
The goal of this project is to help you get enough practice working with bootstrap. That is why it is a requirement to use Bootstrap CSS classes **everywhere** for styling ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/html_css/using_bootstrap/bootstrap_classes_requirement.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/59540308/)). Try to refactor your CSS to rely on as much bootstrap as possible.

__Kindly make the necessary changes and submit another code review request.__
_Feel free to reach me on slack for any inquiries about this review._ :wink: 
__Treasure Kabareebe__

**Comment by Bismarck-GM** [comment]
## Thanks @trekab! ##

- Yes. How I stated in the Pull request milestone comment I started the project making the desktop first (didn't read anywhere about responsiveness and I assumed, wrongly, we didn't need to use it) and I know it was a mistake. 
For me to **not use some custom media queries** I'll have to re-factor the entire page (maybe).

- The **original page uses JavaScript to split/join sections when you change widths**. That's why on mobile I left the left column first. But I can try to sort it out splitting everything before-hand. I might lose the 'stickiness' of the top section.

- I'll make my best to add as many Bootstrap classes I can.

I will create a new pull request as soon as the changes are made.

**Comment by Bismarck-GM** [comment]
## Milestone 2: ##
- Re-factor layout. Instead of 3 main columns now there are 6 splits in 2 rows. So it maintains the TOP-STORY always on top of the webpage.
- Added bootstrap classes to all the parts requested to change.
- Fixed and added navbar hamburger icon and also the ones in the original page below 768px.
- Deleted lots of rules in CSS. It is still long but I tried not to mess with what's already working fine.
- Validated HTML and fixed linter errors.
- Now everything should look on mobile.

PS: I've seen how easy it is working with Bootstrap now. The page dazzled me about how much it was edited and I forgot to keep it simple. 
I've just learned what I edited out of this comment. It was way easier of what I did here with the page... I didn't understand the documentation on Bootstrap first. Now I get how it really works with the sizes.

**Review by sumancrest0001 — CHANGES_REQUESTED** [review]
**STATUS: CHANGES REQUIRED
Well done @Bismarck-GM,**
You have addressed most of the issues raised by the previous TSE. It looks good and most of the requirements are ticked. But we have to make minor changes to the small screen responsiveness. Let's fix them.
[REQUIRED] On small screen other sections look good but we have to fix newsletter, subscribe and footer logo section to get :+1: Subscribe and newsletter section should be only one column but currently, they have two columns. Footer logo, social media should be in a separate row but they are in the same row.

Screenshot from 2020-05-25 08-49-59

Take a reference to the [original page](https://www.newsweek.com/)

Kindly make the above change and request another code review. 
**Need help or have queries regarding the review? DM me on slack **Suman Shrestha**
Happy coding**

**Comment by Bismarck-GM** [comment]
## Thanks @sumancrest0001 for the review.

- Mine also breaks into one column but at lesser resolution. I'll be changing the footer so it works the same as the original page. Also changing the newsletter image that I forgot to add display none.

- I will add more bootstrap classes so I can clean the CSS a little bit more. That's what was all the project about.

**Comment by Bismarck-GM** [comment]
## Milestone 3:

- Changed braking points in footer social links. Below 768px gets below the logo. At 576px the "© 2020 Newsweek" legend does the same.
- Footer newsletter will not display its image below 768px.
- Fixed footer newsletter sizing issues between 768px and 992px.
- Added extra properties to Footer-Subscribe to be pleasing to the eyes below 576px. In the original page its actually broken and the text is not readable.


- Screenshot at 412px wide (Pixel 2 option in Chrome dev-tools)

Screenshot - 2020-05-25T134742 090

**Review by bolah2009 — APPROVED** [review]
It's a 👍🏾 from me!

Good job with the [clone](https://rawcdn.githack.com/Bismarck-GM/Microverse-Using-Bootstrap/bd336a817850f96488b8bae5fc0b4b23403d2c9c/index.html) 👏🏾👏🏾👏🏾
### :heavy_check_mark: Approved!

Good luck with your next projects. :star2: 

Cheers
[Bola](https://bolabuari.com/)

###### PS: Note that comments tagged as `OPTIONAL` are not part of the minimum requirements to approve this PR

**Pull request merged**
